from cooking_handler import food_router
from dormitory_handler import room_router
from edu_handler import edu_router
from flat_handler import flat_router
from job_handler import job_router
from legal_info_handler import law_router
from psychological_support_handler import psy_router
from start_handler import start_router
